export const homeObjOne = {
    id: 'blog',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    headline: 'Rent your home at the best price',
    description: 'More over +999 is waiting for you to find out',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/Boy.png'),
    alt: 'Boy',
    dark: false,
    primary: false,
    darkText: true,
};